### PR TITLE
BIER Header Parsing

### PR DESCRIPTION
**Pull request by Heriam**
added BIER Header Parsing

### CODE REVIEW

**Comment by twatteyne** [comment]
@jmmunoz86, could you please take a look at this PR and pull if works for you?

**Comment by jmmunoz86** [comment]
Yes sir, I'll have a look.

**Comment by jmmunoz86** [comment]
Hello Hao,

did you test this modification against a .pcap file with packets
implementing this BIER draft?

2016-04-16 6:17 GMT+02:00 Jonathan Muñoz jmmunoz86@gmail.com:

> Yes sir, I'll have a look.
> El 16/4/2016 2:04, "Thomas Watteyne" notifications@github.com escribió:
> 
> > @jmmunoz86 https://github.com/jmmunoz86, could you please take a look
> > at this PR and pull if works for you?
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > https://github.com/openwsn-berkeley/dissectors/pull/9#issuecomment-210692544

## 

Jonathan Muñoz

**Comment by Heriam** [comment]
@jmmunoz86 Hello Jonathan, yes I tested with the packets containing BIER header: 

[BIER Packets.pcap.zip](https://github.com/openwsn-berkeley/dissectors/files/222227/BIER.Packets.pcap.zip)

and they would be displayed like this:
image

**Comment by jmmunoz86** [comment]
great! good job!

**Pull request merged**
